const moviesInit = `
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Zack and Miri Make a Porno','Romance',${Math.ceil(Math.random() * 5)},'The Weinstein Company',70,1.747541667,64,'$41.94',2008);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Youth in Revolt','Comedy',${Math.ceil(Math.random() * 5)},'The Weinstein Company',52,1.09,68,'$19.62',2010);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('You Will Meet a Tall Dark Stranger','Comedy',${Math.ceil(Math.random() * 5)},'Independent',35,1.211818182,43,'$26.66',2010);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('When in Rome','Comedy',${Math.ceil(Math.random() * 5)},'Disney',44,0,15,'$43.04',2010);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('What Happens in Vegas','Comedy',${Math.ceil(Math.random() * 5)},'Fox',72,6.267647029,28,'$219.37',2008);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Water For Elephants','Drama',${Math.ceil(Math.random() * 5)},'20th Century Fox',72,3.081421053,60,'$117.09',2011);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('WALL-E','Animation',${Math.ceil(Math.random() * 5)},'Disney',89,2.896019067,96,'$521.28',2008);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Waitress','Romance',${Math.ceil(Math.random() * 5)},'Independent',67,11.0897415,89,'$22.18',2007);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Waiting For Forever','Romance',${Math.ceil(Math.random() * 5)},'Independent',53,0.005,6,'$0.03',2011);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Valentine''s Day','Comedy',${Math.ceil(Math.random() * 5)},'Warner Bros.',54,4.184038462,17,'$217.57',2010);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Tyler Perry''s Why Did I get Married','Romance',${Math.ceil(Math.random() * 5)},'Independent',47,3.7241924,46,'$55.86',2007);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Twilight: Breaking Dawn','Romance',${Math.ceil(Math.random() * 5)},'Independent',68,6.383363636,26,'$702.17',2011);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('Twilight','Romance',${Math.ceil(Math.random() * 5)},'Summit',82,10.18002703,49,'$376.66',2008);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('The Ugly Truth','Comedy',${Math.ceil(Math.random() * 5)},'Independent',68,5.402631579,14,'$205.30',2009);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('The Twilight Saga: New Moon','Drama',${Math.ceil(Math.random() * 5)},'Summit',78,14.1964,27,'$709.82',2009);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('The Time Traveler''s Wife','Drama',${Math.ceil(Math.random() * 5)},'Paramount',65,2.598205128,38,'$101.33',2009);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('The Proposal','Comedy',${Math.ceil(Math.random() * 5)},'Disney',74,7.8675,43,'$314.70',2009);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('The Invention of Lying','Comedy',${Math.ceil(Math.random() * 5)},'Warner Bros.',47,1.751351351,56,'$32.40',2009);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('The Heartbreak Kid','Comedy',${Math.ceil(Math.random() * 5)},'Paramount',41,2.129444167,30,'$127.77',2007);
INSERT INTO "Movies"(film,genre,author_id,lead_studio,audience_score,profitability,rotten_tomatoes,worldwide_gross,year) VALUES ('The Duchess','Drama',${Math.ceil(Math.random() * 5)},'Paramount',68,3.207850222,60,'$43.31',2008);
`
module.exports = { moviesInit }